# CI script for KoraOS on Gitlab
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
image: axfab/kora-gcc:latest

.build:
  stage: build
  script:
    - make clean
    - make
  artifacts:
    paths:
      - bin/kora-$ARCH.krn

test:
  stage: test
  script:
    - make clean
    - make check
    - sh ./scripts/coverage.sh || true
  coverage: 'lines......: [0-9.]*% ([0-9]* of [0-9]* lines)'

publish:
  stage: release
  needs:
    - job: .build
      artifacts: true
  only:
    refs:
      - master
  release:
    name: 'Release $CI_COMMIT_TAG'
    description: 'Created using the release-cli $EXTRA_DESCRIPTION'  # $EXTRA_DESCRIPTION must be defined
    tag_name: '$CI_COMMIT_TAG'                                       # elsewhere in the pipeline.
    ref: '$CI_COMMIT_TAG'

# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
build_i386:
  extends: .build
  variables:
    ARCH: 'i386'
    CROSS: "/opt/bin/i386-elf-"
    target: "i386-pc-kora"

