# CI script for KoraOS on Gitlab
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
image: gcc

build:
  stage: build
  before_script:
    - apt update && apt install -y binutils make gcc nasm
    - ./scripts/toolchain.sh install
  script:
    - make clean
    - make CROSS=./opt/bin/i386-elf- target=x86-pc-kora
  artifacts:
    paths:
      - bin/kImage

test:
  stage: test
  before_script:
    - apt update && apt install -y binutils make gcc nasm lcov valgrind
  script:
    - make clean
    - make check
    - sh ./scripts/coverage.sh || true

