# CI script for KoraOS on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c

services:
  - docker

before_install:
  - docker pull axfab/kora-gcc:latest
  - docker run -v `pwd`:/app -w /app -e LANG=C.UTF-8 -t axfab/kora-gcc:latest bash

  - sudo apt-get update
  - sudo apt-get install -y binutils gcc make

jobs:
  include:
    - stage: build
      env:
      - target=i386-pc-kora
      - CROSS=./opt/bin/i386-elf-
      install:
      - sudo apt-get install -y nasm
      - ./scripts/toolchain.sh install
      script:
      - make clean
      - make
    - stage: test
      install:
      - sudo apt-get install -y lcov valgrind
      script:
      - make clean
      - make check
      after_script:
      - sh ./scripts/coverage.sh || true
