# CI script for KoraOS on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c
before_install:
  - sudo apt-get install -y binutils gcc make nasm lcov valgrind

jobs:
  include:
    - stage: build
      script: ls -s ../`uname -m`/bits/ include/arch/um/bits
      script: make clean
      # script: make kImage
    - stage: test
      script: ls -s ../`uname -m`/bits/ include/arch/um/bits
      script: make clean
      script: make check
      script: sh ./hooks/coverage.sh || true
