# CI script for KoraOS on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c
before_install:
  - sudo apt-get install -y binutils gcc make nasm lcov valgrind
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update
  - sudo apt-get install gcc-8
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 90

jobs:
  include:
    - stage: build
      script: 
      - ln -s ../`uname -m`/bits/ include/arch/um/bits
      - make clean
      # script: make kImage
    - stage: test
      script:
      - ln -s ../`uname -m`/bits/ include/arch/um/bits
      - make clean
      - make check
      - sh ./hooks/coverage.sh || true
