# CI script for KoraOS on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c
before_install:
  - sudo add-apt-repository -y "deb http://archive.ubuntu.com/ubuntu $(lsb_release -sc) main universe restricted multiverse"
  - sudo apt-get update
  - sudo apt-get install -y binutils gcc make

jobs:
  include:
    - stage: build
      env:
      - target=x86-pc-kora
      install:
      - sudo apt-get install -y nasm
#      - sudo apt-get install gcc-8-i686-pc-linux-gnu
#      - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8-i686-pc-linux-gnu 90
      script: 
      - make clean
#      - make kImage
    - stage: test
      install:
      - sudo apt-get install -y lcov valgrind
      script:
      - ln -s ../`uname -m`/bits/ include/arch/um/bits
      - make clean
      - make check
      after_script:
      - sh ./hooks/coverage.sh || true
