# CI script for KoraOS on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c
before_install:
  - sudo apt-get update
  - sudo apt-get install -y binutils gcc make
  - ./hooks/toolchain.sh install

jobs:
  include:
    - stage: build
      env:
      - target=i386-pc-kora
      - CROSS=./opt/bin/i386-elf-
      install:
      - sudo apt-get install -y nasm
      - ln -s x86 include/arch/i386
      script:
      - make clean
      - make kImage
    - stage: test
      install:
      - sudo apt-get install -y lcov valgrind
      script:
      - ln -s ../`uname -m`/bits/ include/arch/um/bits
      - make clean
      - make check
      after_script:
      - sh ./hooks/coverage.sh || true
