# CI script for KoraOS on Travis
# -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
language: c
before_install:
  - sudo apt-get update
  - sudo apt-get install -y binutils gcc make

jobs:
  include:
    - stage: build
      env:
      - target=x86-pc-kora
      - CROSS=./opt/bin/i386-elf-
      install:
      - sudo apt-get install -y nasm
      - ./scripts/toolchain.sh install
      script:
      - make clean
      - make
    - stage: test
      install:
      - sudo apt-get install -y lcov valgrind
      script:
      - make clean
      - make check
      after_script:
      - sh ./scripts/coverage.sh || true
