

# ###########################################
# Drivers
# ###########################################
drivers:
  disk:
    ata: y
  fs:
    isofs: y
    fat: y
    ext2: n
  input:
    ps2: i
  media:
    vga: y
  net:
    e1000: y




